"""add attendance table

Revision ID: 4952b3dcfb78
Revises: 9c3ee84f0198
Create Date: 2026-01-08 13:19:34.418070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4952b3dcfb78'
down_revision: Union[str, None] = '9c3ee84f0198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
