"""Initial schema with correct table names

Revision ID: ca24c5714f83
Revises: 6eef8bf454f0
Create Date: 2026-01-01 17:04:18.288500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca24c5714f83'
down_revision: Union[str, None] = '6eef8bf454f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_task_id'), 'student_task', ['id'], unique=False)
    op.drop_index('ix_student_tasks_id', table_name='student_tasks')
    op.drop_table('student_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='student_tasks_student_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='student_tasks_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_tasks_pkey')
    )
    op.create_index('ix_student_tasks_id', 'student_tasks', ['id'], unique=False)
    op.drop_index(op.f('ix_student_task_id'), table_name='student_task')
    op.drop_table('student_task')
    # ### end Alembic commands ###
