"""add enable_ai_analysis to tasks

Revision ID: d92307c7b838
Revises: 625eae5752b6
Create Date: 2026-01-03 22:33:25.800911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92307c7b838'
down_revision: Union[str, None] = '625eae5752b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('enable_ai_analysis', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'enable_ai_analysis')
    # ### end Alembic commands ###
