"""Initial schema with correct table namessss

Revision ID: ef2668879c12
Revises: ca24c5714f83
Create Date: 2026-01-01 18:27:00.118915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2668879c12'
down_revision: Union[str, None] = 'ca24c5714f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_task', sa.Column('status', sa.String(), nullable=True))
    op.add_column('student_task', sa.Column('teacher_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_task', 'teacher_comment')
    op.drop_column('student_task', 'status')
    # ### end Alembic commands ###
